#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/../.." && pwd)"

target_dir="${XLOG_RUSTDOC_TARGET_DIR:-$repo_root/target/docs-rustdoc}"
output_dir="${XLOG_RUSTDOC_OUTPUT_DIR:-$repo_root/.site-rustdoc/generated/rust}"

cd "$repo_root"

XLOG_RUSTDOC_NO_CUDA=1 cargo doc --workspace --no-deps --locked --target-dir "$target_dir"

rm -rf "$output_dir"
mkdir -p "$(dirname "$output_dir")"
cp -R "$target_dir/doc" "$output_dir"
find "$output_dir" -type f -name '*.md' -delete

{
    cat <<'HTML'
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>XLOG Rust API</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    body { font-family: system-ui, sans-serif; margin: 2rem; line-height: 1.5; }
    code { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; }
  </style>
</head>
<body>
  <h1>XLOG Rust API</h1>
  <p>This index is generated by <code>scripts/docs/build_rust_api.sh</code> from the current workspace rustdoc output.</p>
  <ul>
HTML
    find "$output_dir" -mindepth 1 -maxdepth 1 -type d | sort | while read -r crate_dir; do
        crate="$(basename "$crate_dir")"
        if [[ -f "$crate_dir/index.html" ]]; then
            printf '    <li><a href="%s/index.html"><code>%s</code></a></li>\n' "$crate" "$crate"
        fi
    done
    cat <<'HTML'
  </ul>
</body>
</html>
HTML
} > "$output_dir/index.html"

echo "Rust API docs generated at $output_dir"
