#!/usr/bin/env python3
"""Generate Markdown API reference from pyxlog type stubs."""

from __future__ import annotations

import argparse
import ast
from pathlib import Path
import sys
from typing import Iterable


DEFAULT_STUB = Path("crates/pyxlog/python/pyxlog/_native.pyi")


def format_arg(arg: ast.arg, default: ast.expr | None = None) -> str:
    text = arg.arg
    if arg.annotation is not None:
        text += f": {ast.unparse(arg.annotation)}"
    if default is not None:
        text += f" = {ast.unparse(default)}"
    return text


def format_arguments(args: ast.arguments) -> str:
    positional = list(args.posonlyargs) + list(args.args)
    positional_defaults: list[ast.expr | None] = [None] * (
        len(positional) - len(args.defaults)
    ) + list(args.defaults)
    parts = [
        format_arg(arg, default)
        for arg, default in zip(positional, positional_defaults)
    ]
    if args.vararg is not None:
        parts.append("*" + format_arg(args.vararg))
    elif args.kwonlyargs:
        parts.append("*")
    for arg, default in zip(args.kwonlyargs, args.kw_defaults):
        parts.append(format_arg(arg, default))
    if args.kwarg is not None:
        parts.append("**" + format_arg(args.kwarg))
    return ", ".join(parts)


def function_signature(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    prefix = "async def" if isinstance(node, ast.AsyncFunctionDef) else "def"
    returns = f" -> {ast.unparse(node.returns)}" if node.returns is not None else ""
    return f"{prefix} {node.name}({format_arguments(node.args)}){returns}"


def class_attributes(node: ast.ClassDef) -> Iterable[str]:
    for item in node.body:
        if isinstance(item, ast.AnnAssign) and isinstance(item.target, ast.Name):
            yield f"{item.target.id}: {ast.unparse(item.annotation)}"


def class_methods(node: ast.ClassDef) -> Iterable[ast.FunctionDef | ast.AsyncFunctionDef]:
    for item in node.body:
        if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef)):
            yield item


def render_docstring(node: ast.AST) -> list[str]:
    docstring = ast.get_docstring(node)
    if not docstring:
        return []
    return [docstring.strip(), ""]


def render_module(source: str, source_label: str) -> str:
    module = ast.parse(source)
    lines = [
        "# pyxlog Python API",
        "",
        f"Generated from `{source_label}`. Do not edit this file by hand.",
        "",
    ]

    top_level_functions: list[ast.FunctionDef | ast.AsyncFunctionDef] = []
    for item in module.body:
        if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef)):
            top_level_functions.append(item)
        if not isinstance(item, ast.ClassDef):
            continue

        lines.extend([f"## {item.name}", ""])
        lines.extend(render_docstring(item))

        attrs = list(class_attributes(item))
        if attrs:
            lines.extend(["### Attributes", ""])
            for attr in attrs:
                lines.extend(["```python", attr, "```", ""])

        methods = list(class_methods(item))
        if methods:
            lines.extend(["### Methods", ""])
            for method in methods:
                lines.extend(["```python", f"{function_signature(method)}: ...", "```", ""])
                lines.extend(render_docstring(method))

    if top_level_functions:
        lines.extend(["## Module functions", ""])
        for fn in top_level_functions:
            lines.extend(["```python", f"{function_signature(fn)}: ...", "```", ""])
            lines.extend(render_docstring(fn))

    return "\n".join(lines).rstrip() + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=DEFAULT_STUB)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--stdin", action="store_true", help="Read stub source from stdin")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.stdin:
        source = sys.stdin.read()
        source_label = "<stdin>"
    else:
        source = args.input.read_text(encoding="utf-8")
        source_label = str(args.input)

    rendered = render_module(source, source_label)
    if args.output is None:
        sys.stdout.write(rendered)
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
