//! Provenance records for generated induction candidates.

/// Origin class for a rule emitted by induction.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RuleSourceKind {
    /// Rule was generated by an induction/search process.
    Generated,
}

/// One positive support row retained for an induced rule.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InductionSupportRow {
    /// Relation that supplied the row.
    pub relation: String,
    /// Stable row offset in the relation snapshot used for search.
    pub row_index: u64,
    /// Caller-supplied stable row hash.
    pub row_hash: String,
}

impl InductionSupportRow {
    /// Construct a support-row record.
    pub fn new(relation: impl Into<String>, row_index: u64, row_hash: impl Into<String>) -> Self {
        Self {
            relation: relation.into(),
            row_index,
            row_hash: row_hash.into(),
        }
    }
}

/// One rejected candidate alternative retained for audit.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InductionAlternative {
    /// Candidate rule source.
    pub rule_source: String,
    /// Positive examples covered by this alternative.
    pub support_count: u64,
    /// Counterexamples or falsifications found for this alternative.
    pub falsification_count: u64,
}

impl InductionAlternative {
    /// Construct a rejected-alternative record.
    pub fn new(
        rule_source: impl Into<String>,
        support_count: u64,
        falsification_count: u64,
    ) -> Self {
        Self {
            rule_source: rule_source.into(),
            support_count,
            falsification_count,
        }
    }
}

/// First-class provenance for a mined/generated rule.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InducedRuleProvenance {
    /// Stable generated rule id.
    pub rule_id: String,
    /// Generated rule source text.
    pub rule_source: String,
    /// Rule origin class.
    pub source_kind: RuleSourceKind,
    /// Number of candidates in the search space.
    pub search_space_size: u64,
    /// Predicate inventory considered by the search.
    pub predicate_inventory: Vec<String>,
    /// Positive support rows retained for audit.
    pub support_rows: Vec<InductionSupportRow>,
    /// Rejected alternatives retained for audit.
    pub rejected_alternatives: Vec<InductionAlternative>,
    /// Falsification count for the selected rule.
    pub falsification_count: u64,
    /// Stable hash of the generation trace.
    pub generation_trace_hash: String,
}

impl InducedRuleProvenance {
    /// Construct generated-rule provenance from the selected rule and search inventory.
    pub fn new(
        rule_source: impl Into<String>,
        search_space_size: u64,
        predicate_inventory: Vec<String>,
    ) -> Self {
        let rule_source = rule_source.into();
        let generation_trace_hash = stable_hash(&format!(
            "{}|{}|{}",
            rule_source,
            search_space_size,
            predicate_inventory.join(",")
        ));
        Self {
            rule_id: format!("rule:generated:{}", generation_trace_hash),
            rule_source,
            source_kind: RuleSourceKind::Generated,
            search_space_size,
            predicate_inventory,
            support_rows: Vec::new(),
            rejected_alternatives: Vec::new(),
            falsification_count: 0,
            generation_trace_hash,
        }
    }

    /// Attach positive support rows.
    pub fn with_support_rows(mut self, support_rows: Vec<InductionSupportRow>) -> Self {
        self.support_rows = support_rows;
        self
    }

    /// Attach rejected alternatives.
    pub fn with_rejected_alternatives(
        mut self,
        rejected_alternatives: Vec<InductionAlternative>,
    ) -> Self {
        self.rejected_alternatives = rejected_alternatives;
        self
    }

    /// Attach selected-rule falsification count.
    pub fn with_falsification_count(mut self, falsification_count: u64) -> Self {
        self.falsification_count = falsification_count;
        self
    }
}

/// In-memory registration surface for generated-rule provenance.
#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub struct InductionProvenanceRegistry {
    rules: Vec<InducedRuleProvenance>,
}

impl InductionProvenanceRegistry {
    /// Create an empty provenance registry.
    pub fn new() -> Self {
        Self::default()
    }

    /// Register one generated rule provenance record.
    pub fn register(&mut self, provenance: InducedRuleProvenance) {
        self.rules.push(provenance);
    }

    /// Return registered generated-rule provenance records.
    pub fn rules(&self) -> &[InducedRuleProvenance] {
        &self.rules
    }
}

fn stable_hash(value: &str) -> String {
    let mut hash = 0xcbf29ce484222325u64;
    for byte in value.as_bytes() {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x100000001b3);
    }
    format!("{:016x}", hash)
}
